# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
 
    working_directory: ~/elyrath
 
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx512m
    
    steps:
      - checkout
 
      # Download and cache dependencies
      - restore_cache:
          key: elyrath-{{ checksum "pom.xml" }}
 
      - run: mvn dependency:go-offline
 
      - save_cache:
          paths:
            - ~/.m2
          key: elyrath-{{ checksum "pom.xml" }}
        
      # run tests!
      - run: mvn test

      - run: mvn package
